language: go
go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - release
  - tip

script:
  - (go version | grep "version go1.1") || go get golang.org/x/tools/cmd/vet
  - go get github.com/kisielk/errcheck
  - go get ./...

  - go vet ./...
  - go test -v ./...
  - go test -race ./...
  - errcheck github.com/DATA-DOG/go-sqlmock

